
const GET_ACCOUNT_REQUEST = "GET_ACCOUNT_REQUEST";
const GET_ACCOUNT_SUCCESS = "GET_ACCOUNT_SUCCESS";
const GET_ACCOUNT_FAIL = "GET_ACCOUNT_FAIL";
const CHANGE_ACCOUNT_REQUEST = "CHANGE_ACCOUNT_REQUEST";
const CHANGE_ACCOUNT_SUCCESS = "CHANGE_ACCOUNT_SUCCESS";
const CHANGE_ACCOUNT_FAIL = "CHANGE_ACCOUNT_FAIL";


export {
    GET_ACCOUNT_REQUEST ,
    GET_ACCOUNT_SUCCESS,
    GET_ACCOUNT_FAIL,
    CHANGE_ACCOUNT_REQUEST ,
    CHANGE_ACCOUNT_SUCCESS,
    CHANGE_ACCOUNT_FAIL  
};
