const AUTH_LOGIN_REQ = "AUTH_LOGIN_REQ";
const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
const AUTH_LOGIN_FAILED = "AUTH_LOGIN_FAILED";
export { AUTH_LOGIN_REQ, AUTH_LOGIN_SUCCESS, AUTH_LOGIN_FAILED };
