const BOOKING_TICKET_REQUEST = "BOOKING_TICKET_REQUEST";
const BOOKING_TICKET_SUCCESS = "BOOKING_TICKET_SUCCESS";
const BOOKING_TICKET_FAIL = "BOOKING_TICKET_FAIL";


export {
    BOOKING_TICKET_REQUEST,
    BOOKING_TICKET_SUCCESS,
    BOOKING_TICKET_FAIL,
};
