const BOOKING_TICKET_REQUEST = "BOOKING_TICKET_REQUEST";
const BOOKING_TICKET_SUCCESS = "BOOKING_TICKET_SUCCESS";
const BOOKING_TICKET_FAIL = "BOOKING_TICKET_FAIL";

const GET_LIST_SET_REQUEST = "GET_LIST_SET_REQUEST";
const GET_LIST_SET_SUCCESS = "GET_LIST_SET_SUCCESS";
const GET_LIST_SET_FAIL = "GET_LIST_SET_FAIL";


export {
    BOOKING_TICKET_REQUEST,
    BOOKING_TICKET_SUCCESS,
    BOOKING_TICKET_FAIL,
    GET_LIST_SET_REQUEST ,
    GET_LIST_SET_SUCCESS,
    GET_LIST_SET_FAIL 
};
