const GET_MOVIE_LIST_REQUEST = "GET_MOVIE_LIST_REQUEST";
const GET_MOVIE_LIST_SUCCESS = "GET_MOVIE_LIST_SUCCESS";
const GET_MOVIE_LIST_FAIL = "GET_MOVIE_LIST_FAIL";
const GET_MOVIE_LIST_UPCOMING_REQUEST = "GET_MOVIE_LIST_UPCOMING_REQUEST";
const GET_MOVIE_LIST_UPCOMING_SUCCESS = "GET_MOVIE_LIST_UPCOMING_SUCCESS";
const GET_MOVIE_LIST_UPCOMING_FAIL = "GET_MOVIE_LIST_UPCOMING_FAIL";
const GET_MOVIE_DETAIL_REQUEST = "GET_MOVIE_DETAIL_REQUEST";
const GET_MOVIE_DETAIL_FAILED = "GET_MOVIE_DETAIL_FAILED";
const GET_MOVIE_DETAIL_SUCCESS = "GET_MOVIE_DETAIL_SUCCESS";
const GET_MOVIE_DETAIL_SCHEDULE_SUCCESS = "GET_MOVIE_DETAIL_SCHEDULE_SUCCESS";
const GET_MOVIE_DETAIL_SCHEDULE_FAILED = "GET_MOVIE_DETAIL_SCHEDULE_FAILED";
const RESET_MOVIE_DETAIL_SCHEDULE = "RESET_MOVIE_DETAIL_SCHEDULE";
export {
  GET_MOVIE_LIST_REQUEST,
  GET_MOVIE_LIST_SUCCESS,
  GET_MOVIE_LIST_FAIL,
  GET_MOVIE_LIST_UPCOMING_REQUEST,
  GET_MOVIE_LIST_UPCOMING_SUCCESS,
  GET_MOVIE_LIST_UPCOMING_FAIL,
  GET_MOVIE_DETAIL_FAILED,
  GET_MOVIE_DETAIL_REQUEST,
  GET_MOVIE_DETAIL_SUCCESS,
  GET_MOVIE_DETAIL_SCHEDULE_SUCCESS,
  GET_MOVIE_DETAIL_SCHEDULE_FAILED,
  RESET_MOVIE_DETAIL_SCHEDULE,
};
