const GET_MOVIE_LIST_REQUEST = "GET_MOVIE_LIST_REQUEST";
const GET_MOVIE_LIST_SUCCESS = "GET_MOVIE_LIST_SUCCESS";
const GET_MOVIE_LIST_FAIL = "GET_MOVIE_LIST_FAIL";

const LOGIN_REQUEST = "LOGIN_REQUEST";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAIL = "LOGIN_FAIL";

const GET_MOVIE_DETAIL_REQUEST = "GET_MOVIE_DETAIL_REQUEST";
const GET_MOVIE_DETAIL_FAILED = "GET_MOVIE_DETAIL_FAILED";
const GET_MOVIE_DETAIL_SUCCESS = "GET_MOVIE_DETAIL_SUCCESS";
export {
  GET_MOVIE_LIST_REQUEST,
  GET_MOVIE_LIST_SUCCESS,
  GET_MOVIE_LIST_FAIL,
  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_FAIL,
  GET_MOVIE_DETAIL_FAILED,
  GET_MOVIE_DETAIL_REQUEST,
  GET_MOVIE_DETAIL_SUCCESS,
};
