const GET_THEATER_LIST_REQUEST = "GET_THEATER_LIST_REQUEST";
const GET_THEATER_LIST_SUCCESS = "GET_THEATER_LIST_SUCCESS";
const GET_THEATER_LIST_FAIL = "GET_THEATER_LIST_FAIL";

const GET_THEATER_KIND_LIST_REQUEST = "GET_THEATER_KIND_LIST_REQUEST";
const GET_THEATER_KIND_LIST_SUCCESS = "GET_THEATER_KIND_LIST_SUCCESS";
const GET_THEATER_KIND_LIST_FAIL = "GET_THEATER_KIND_LIST_FAIL";

export {
  GET_THEATER_LIST_REQUEST,
  GET_THEATER_LIST_SUCCESS,
  GET_THEATER_LIST_FAIL,
  GET_THEATER_KIND_LIST_REQUEST,
  GET_THEATER_KIND_LIST_SUCCESS,
  GET_THEATER_KIND_LIST_FAIL
};
