const GET_THEATER_LIST_REQUEST = "GET_THEATER_LIST_REQUEST";
const GET_THEATER_LIST_SUCCESS = "GET_THEATER_LIST_SUCCESS";
const GET_THEATER_LIST_FAIL = "GET_THEATER_LIST_FAIL";
const GET_THEATER_BRAND_REQUEST = "GET_THEATER_BRAND_REQUEST";
const GET_THEATER_BRAND_SUCCESS = "GET_THEATER_BRAND_SUCCESS";
const GET_THEATER_BRAND_FAILED = "GET_THEATER_BRAND_FAILED";
const RESET_THEATER_BRAND_LIST = "RESET_THEATER_BRAND_LIST";

const GET_THEATER_ADDRESSES_SUCCESS = "GET_THEATER_ADDRESSES_SUCCESS";
const GET_THEATER_ADDRESSES_FAILED = "GET_THEATER_ADDRESSES_FAILED";
export {
  GET_THEATER_LIST_REQUEST,
  GET_THEATER_LIST_SUCCESS,
  GET_THEATER_LIST_FAIL,
  GET_THEATER_BRAND_SUCCESS,
  GET_THEATER_BRAND_REQUEST,
  GET_THEATER_BRAND_FAILED,
  RESET_THEATER_BRAND_LIST,
  GET_THEATER_ADDRESSES_SUCCESS,
  GET_THEATER_ADDRESSES_FAILED,
};
